name: Prebuild

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install
      run: |
        npm ci
    - name: test
      run: |
        npm test
      env:
        CI: true
    - name: publish
      run: |
        npx node-pre-gyp build
        npx node-pre-gyp package
        npx node-pre-gyp-github publish --release
      env:
        CI: true
        NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    name: Publish package release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: publish to npmjs.com
      run: |
        npm publish --access public
      env:
         NPM_TOKEN: ${{secrets.NPM_TOKEN}}
